name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    name: Tests + Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          default: true
          components: clippy, rustfmt
          target: wasm32-wasip1

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
        
      - name: Cargo target cache
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: Tests
        run: make test

      - name: Lint
        run: make fmt
